### ISSUE TITLE
The set-output command is deprecated and will be disabled in June 2023

### ISSUE THREAD

**Issue by zer0Kerbal** [KSP-CKAN/KSPMMCfgParser#16] opened 2022-11-05 06:38 UTC
The `save-state` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by HebaruSan** [comment] 2022-11-06 16:04
Looking into this, it doesn't seem like this is submitted in the right place. The only occurrence of save-state or set-output anywhere in this repo is in our own workflows, which will need to be updated before the deadline, but which would not affect any other projects.

Can I ask why you thought this project was responsible for this warning?

**Comment by HebaruSan** [comment] 2022-11-06 16:08
For reference, these are the places in the KSP-CKAN org where we use `set-output` (we don't use `save-state` anywhere):

https://github.com/KSP-CKAN/KSPMMCfgParser/blob/16e84099d137431107c3fdaacc9dbebe355065e1/.github/workflows/release.yml#L28-L32

https://github.com/KSP-CKAN/CKAN/blob/3dfcf3edf86bd316eaf9c6aa807bf643ad770548/.github/workflows/release.yml#L58-L66

https://github.com/KSP-CKAN/CKAN/blob/3dfcf3edf86bd316eaf9c6aa807bf643ad770548/.github/workflows/deploy.yml#L27-L32

**Comment by HebaruSan** [comment] 2022-11-06 18:46
OK, as of KSP-CKAN/CKAN#3696 and #17, I think all uses of `set-output` in the KSP-CKAN org are eliminated.
But note that this won't fix whatever problem you were having, because this wasn't the cause of it, as noted.

**Closed as completed by HebaruSan** 2022-11-06 18:46 UTC
Labels: invalid, question

**Comment by zer0Kerbal** [comment] 2022-11-07 04:40
this has been showing up when using the action:

Just wanted you to know - in case it was going to break the action.

Happy belated 🎃

![image](https://user-images.githubusercontent.com/39887717/200227833-f0b226ad-f4e5-4799-8b2e-ef8d62ec64d0.png)

**Comment by HebaruSan** [comment] 2022-11-07 04:44
Yeah, that's not from anything we're doing. Some other part of the workflow is triggering that.

**Comment by zer0Kerbal** [comment] 2022-11-07 05:03
okay.
